# Generated by Django 4.0.3 on 2022-03-31 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homeowner_family_code'),
        ('logging_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='name',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.homeowner'),
        ),
    ]
