# Generated by Django 4.0.3 on 2022-03-31 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0002_remove_log_name_log_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log_info',
        ),
    ]
