# Generated by Django 4.0.3 on 2022-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0003_delete_log_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
