# Generated by Django 4.0.3 on 2022-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0005_alter_log_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
