# Generated by Django 4.0.3 on 2022-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0006_alter_log_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='visitor_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
